//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouchKB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TouchKB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AltGrActiveKeyPressed {
            get {
                object obj = ResourceManager.GetObject("AltGrActiveKeyPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AltGrActiveKeyReleased {
            get {
                object obj = ResourceManager.GetObject("AltGrActiveKeyReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AltGrKeyPressed {
            get {
                object obj = ResourceManager.GetObject("AltGrKeyPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AltGrKeyReleased {
            get {
                object obj = ResourceManager.GetObject("AltGrKeyReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackspaceKeyPressed {
            get {
                object obj = ResourceManager.GetObject("BackspaceKeyPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackspaceKeyReleased {
            get {
                object obj = ResourceManager.GetObject("BackspaceKeyReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CapsLockActiveKeyMedPressed {
            get {
                object obj = ResourceManager.GetObject("CapsLockActiveKeyMedPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CapsLockActiveKeyMedReleased {
            get {
                object obj = ResourceManager.GetObject("CapsLockActiveKeyMedReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CapsLockKeyMedPressed {
            get {
                object obj = ResourceManager.GetObject("CapsLockKeyMedPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CapsLockKeyMedReleased {
            get {
                object obj = ResourceManager.GetObject("CapsLockKeyMedReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyPressed {
            get {
                object obj = ResourceManager.GetObject("KeyPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyReleased {
            get {
                object obj = ResourceManager.GetObject("KeyReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftKeyPressed {
            get {
                object obj = ResourceManager.GetObject("LeftKeyPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftKeyReleased {
            get {
                object obj = ResourceManager.GetObject("LeftKeyReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightKeyPressed {
            get {
                object obj = ResourceManager.GetObject("RightKeyPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightKeyReleased {
            get {
                object obj = ResourceManager.GetObject("RightKeyReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShiftActiveKeyPressed {
            get {
                object obj = ResourceManager.GetObject("ShiftActiveKeyPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShiftActiveKeyReleased {
            get {
                object obj = ResourceManager.GetObject("ShiftActiveKeyReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShiftKeyPressed {
            get {
                object obj = ResourceManager.GetObject("ShiftKeyPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShiftKeyReleased {
            get {
                object obj = ResourceManager.GetObject("ShiftKeyReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpacebarKeyPressed {
            get {
                object obj = ResourceManager.GetObject("SpacebarKeyPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpacebarKeyReleased {
            get {
                object obj = ResourceManager.GetObject("SpacebarKeyReleased", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
